export const WorkData = [
  {
    id: "0",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Software Engineer",
    roles: "Lead Frontend Developer, Fullstack, UI/UX, Scrum Master",
    skills: ["React", "Javascript", "SQL", "Java", "Web", "Dev"],
    date: "May 2021 - Present",
    location: "Redondo Beach, CA",
    jobDescription: [
      "Level two software engineer working as the lead frontend developer of a team of six.",
      "Skills: React, Java, SQL, Java Script, HTML, CSS, Agile, Astro UXDS",
      "Roles and Responsabilities:",
      "- Develops interfaces following designs provided by UI designers",
      "- Designs frontend architecture",
      "- Develops software solutions by studying information needs, user needs, and studying systems flow, data usage, and work processes.",
      "- Follows the software development lifecycle",
      "- Documents and demonstrates solutions by developing documentation, diagrams, charts, code comments, and clear code",
      "- Protects operations by keeping information confidential",
      "- Designs UI solutions addressing the needs of the end user",
      "- Leads team in daily Scrum standup, bi-weekly end of sprint prosedure, and documents sprint data ",
      "- Leads team in daily Scrum standup, bi-weekly end of sprint prosedure, and documents sprint data ",
    ],
  },
  {
    id: "1",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Associate Software Engineer",
    roles: "Lead Frontend Developer",
    skills: ["Oragami", "Javascript", "HTML", "CSS", "Web Dev"],
    date: "Feb 2021 - June 2021",
    location: "Huntsville, AL - Remote from CA",
    jobDescription: ["Worked as a software engineer"],
  },
  {
    id: "2",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Associate Software Engineer",
    roles: "Frontend Developer",
    skills: ["Oragami", "Javascript", "HTML", "CSS", "Mobile App Dev"],
    date: "Feb 2021 - May 2021",
    location: "Huntsville, AL - Remote from CA",
    jobDescription: ["Worked as a software engineer"],
  },
  {
    id: "3",
    type: "school",
    companyName: "Azusa Pacific University",
    position: "B.S. Computer Science",
    roles: "Suma Cum Laude",
    skills: ["GPA: 3.83"],
    date: "December 2020",
    location: "Azusa, CA",
    jobDescription: ["Worked as a software engineer"],
  },
];

export default WorkData;
