export const WorkData = [
  {
    id: "0",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Software Engineer",
    roles: "Lead Frontend Developer, Fullstack, UI/UX, Scrum Master",
    skills: "React | Javascript | SQL | Java | Web Dev",
    date: "May 2021 - Present",
    location: "Redondo Beach, CA",
    jobDescription: "Worked as a software engineer",
  },
  {
    id: "1",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Associate Software Engineer",
    roles: "Lead Frontend Developer",
    skills: "Oragami | Javascript | HTML | CSS | Web Dev",
    date: "Feb 2021 - June 2021",
    location: "Huntsville, AL - Remote from CA",
    jobDescription: "Worked as a software engineer",
  },
  {
    id: "2",
    type: "job",
    companyName: "Northrop Grumman",
    position: "Associate Software Engineer",
    roles: "Frontend Developer",
    skills: "Oragami   | Javascript | HTML | CSS | Mobile App Dev",
    date: "Feb 2021 - May 2021",
    location: "Huntsville, AL - Remote from CA",
    jobDescription: "Worked as a software engineer",
  },
  {
    id: "3",
    type: "school",
    companyName: "Azusa Pacific University",
    position: "B.S. Computer Science",
    roles: "Suma Cum Laude",
    skills: "GPA: 3.83",
    date: "December 2020",
    location: "Azusa, CA",
    jobDescription: "Worked as a software engineer",
  },
];

export default WorkData;
